import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
const $=id=>document.getElementById(id),rad=THREE.MathUtils.degToRad;
async function main(){
 const response=await fetch('scene.json');if(!response.ok)throw new Error('The ship geometry could not be loaded.');const data=await response.json();
 const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true,logarithmicDepthBuffer:true});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.NoToneMapping;$('viewport').appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Enterprise-D ship geometry');
 const scene=new THREE.Scene();scene.background=new THREE.Color('#02050b');const camera=new THREE.PerspectiveCamera(58,1,.04,10000);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=.3;controls.maxDistance=2000;
 scene.add(new THREE.HemisphereLight('#f5ecdc','#8994a5',1.6));const sun=new THREE.DirectionalLight('#d9e9ff',1.8);sun.position.set(-450,800,500);scene.add(sun);const fill=new THREE.DirectionalLight('#799cff',.4);fill.position.set(400,300,-800);scene.add(fill);
 const configResponse=await fetch('config.json');if(!configResponse.ok)throw new Error('The preview configuration is missing. Run tools/prepare_preview.py.');const config=await configResponse.json();
 const textureLoader=new THREE.TextureLoader(),textures={};for(const name of new Set(Object.values(data.materials).map(m=>m.texture).filter(Boolean))){const t=await textureLoader.loadAsync(config.textureBase+name+'.jpg');t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.anisotropy=4;textures[name]=t;}
 const materials={};for(const [name,m] of Object.entries(data.materials)){const params={color:new THREE.Color(...m.color).convertSRGBToLinear(),map:textures[m.texture]||null,side:THREE.DoubleSide,transparent:(m.opacity??1)<1,opacity:m.opacity??1,depthWrite:(m.opacity??1)>=1};materials[name]=m.unlit?new THREE.MeshBasicMaterial(params):new THREE.MeshStandardMaterial({...params,roughness:.8,metalness:.12});}
 function sign(action){const text=action.match(/\bsign\s+"([^"]+)"/)?.[1];if(!text)return materials.sign;const c=document.createElement('canvas');c.width=1024;c.height=256;const x=c.getContext('2d');x.fillStyle='#101218';x.fillRect(0,0,1024,256);x.fillStyle='#ffcc99';x.font='500 72px Arial';while(x.measureText(text).width>950){const size=parseInt(x.font.match(/(\d+)px/)[1])-2;x.font='500 '+size+'px Arial';}x.textAlign='center';x.textBaseline='middle';x.fillText(text,512,128);const t=new THREE.CanvasTexture(c);t.flipY=false;t.colorSpace=THREE.SRGBColorSpace;return new THREE.MeshBasicMaterial({map:t,side:THREE.DoubleSide});}
 const meshes=new Map();for(const model of data.models){const group=new THREE.Group();for(const p of model.parts){let g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p.vertices.flat(),3));g.setAttribute('uv',new THREE.Float32BufferAttribute(p.uv.flat(),2));g.setIndex(p.triangles.flat());g=g.toNonIndexed();g.computeVertexNormals();const mesh=new THREE.Mesh(g,materials[p.material]);mesh.userData.material=p.material;group.add(mesh);}meshes.set(model.name,group);}
 let total=0;for(const p of data.placements){const source=meshes.get(p.model);if(!source)throw new Error('Missing model '+p.model);const group=source.clone();group.position.fromArray(p.position);group.rotation.set(rad(p.tilt||0),rad(p.yaw||0),rad(p.roll||0));for(const mesh of group.children){if(mesh.userData.material==='sign')mesh.material=sign(p.action||'');total+=mesh.geometry.attributes.position.count/3;}scene.add(group);}
 const sky=meshes.get(data.skybox);if(sky)scene.add(sky);
 const descriptions={Bridge:'Command stations and the captain’s chair. Use the amber destination panels in the rear lift lobby.', 'Ten Forward':'A quiet lounge at the saucer’s forward edge. Panoramic windows, tables and a curved bar overlook the planet.',Engineering:'Explore the warp core, diagnostic consoles and upper galleries. A real ramp connects both levels.'};
 let selected=-1;function cameraFor(d){if(d.camera?.position&&d.camera?.target)return[d.camera.position,d.camera.target];const p=[d.x,d.y,d.z],a=rad(d.yaw||0);return[p,[p[0]+Math.sin(a)*8,p[1],p[2]+Math.cos(a)*8]];}
 function move(p,t){camera.position.fromArray(p);controls.target.fromArray(t);controls.update();}
 function choose(i){selected=i;const d=data.destinations[i];move(...cameraFor(d));$('view-mode').textContent=d.category||'INTERIOR';$('category').textContent='ENTERPRISE-D / '+(d.category||'DECK ACCESS');$('location').textContent=d.name;$('description').textContent=d.description||descriptions[d.name]||'Explore this part of the Enterprise-D.';$('coordinates').textContent=d.coordinates;$('copy').hidden=false;document.querySelectorAll('nav button').forEach((b,n)=>{b.classList.toggle('active',n===i);b.setAttribute('aria-pressed',String(n===i));});}
 function exterior(){selected=-1;move([-410,300,480],[0,95,-35]);$('view-mode').textContent='EXTERIOR SURVEY';$('category').textContent='GALAXY CLASS / EXTERIOR';$('location').textContent='U.S.S. Enterprise-D';$('description').textContent='The broad saucer, swept nacelles and blue deflector of the Enterprise-D. Choose a deck to step inside, or visit the observation platform and take flight.';$('coordinates').textContent='StarTrek · P100 · first release';$('copy').hidden=true;document.querySelectorAll('nav button').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false');});}
 for(const [i,d] of data.destinations.entries()){const b=document.createElement('button');const n=document.createElement('span');n.className='num';n.textContent=String(i+1).padStart(2,'0');const p=document.createElement('span');p.className='place';p.textContent=d.name;const deck=document.createElement('span');deck.className='deck';deck.textContent=d.category||'INTERIOR / TURBOLIFT ACCESS';p.appendChild(deck);b.append(n,p);b.addEventListener('click',()=>choose(i));$('destinations').appendChild(b);}
 $('count').textContent=String(data.destinations.length).padStart(2,'0');$('overview').onclick=exterior;$('copy').onclick=async()=>{if(selected<0)return;try{await navigator.clipboard.writeText(data.destinations[selected].coordinates);$('copy').textContent='Copied';setTimeout(()=>$('copy').textContent='Copy coordinates',1400);}catch{$('copy').textContent='Select coordinates to copy';}};
 $('scene-status').textContent=data.placements.length.toLocaleString()+' native objects · '+data.models.length+' original models';$('scene-status').dataset.objects=data.placements.length;$('scene-status').dataset.triangles=total;$('scene-status').dataset.ready='true';
 function resize(){const r=$('viewport').getBoundingClientRect();renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe($('viewport'));resize();exterior();$('loading').classList.add('done');
 let dirty=true;controls.addEventListener('change',()=>dirty=true);window.addEventListener('resize',()=>dirty=true);
 function frame(){requestAnimationFrame(frame);controls.update();if(dirty){if(sky)sky.position.copy(camera.position);renderer.render(scene,camera);dirty=false;}}requestAnimationFrame(frame);
}
main().catch(e=>{$('load-message').textContent=e.message;console.error(e);});
